### PR TITLE
Adding a hint of how to use system

### PR DESCRIPTION
**Pull request by drusellers**

### CODE REVIEW

**Comment by stuartsierra** [comment]
This comment suggests accessing the "system" object directly in application code, which I do not recommend.

**Comment by drusellers** [comment]
So, then I guess I'm at a loss - how do you then use the system reference if not like this?

**Comment by ddossot** [comment]
You do not need to use the "system" directly but instead receive the components you need by injection.

**Comment by drusellers** [comment]
Ok, I think I'm starting to see my issue.  How do the 'functions' get access then? Ok, so I need a protocol that my record can implement (makes sense) right? then I can add functions to it, that won't need to be passed in because i can get them from the protocol - but at the highest entry point won't something have to dig into system - hmm. maybe not. I need to think through how this is done with compojure clearly, as that is my starting point. But given compojure - because of the static nature it would need to 'dig' into the system - but if I could build my routes like a component then I would be good to go.

**Comment by stuartsierra** [comment]
Please move this discussion to the [Clojure Mailing List](https://groups.google.com/forum/#!forum/clojure) where more people will be able to offer advice.

**Comment by drusellers** [comment]
@stuartsierra already has, https://groups.google.com/forum/#!topic/clojure/A5oqstYWhg8

**Pull request closed without merging**
